apiVersion: v1
kind: Service
metadata:
  name: create-account-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: create-account-service
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP