apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app/k8s
    repoURL: 'https://github.com/algorithm24/app.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      seflHeal: true
