apiVersion: v1
kind: Service
metadata:
  name: login-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: login-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP