apiVersion: v1
kind: Service
metadata:
  name: item-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: item-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP