name: CI
on:
  push:
    branches: 
      - master
    paths:
      - 'app/services/docker-compose.yml'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Run Test
        run: python3 -m unittest app/test/test.py
        
      - name: Docker Compose
        run: docker-compose -f app/services/docker-compose.yml build
        
      - name: Push Images to Docker Hub
        run: docker-compose -f app/services/docker-compose.yml push